In [1]:
import b_new

In [2]:
filename_new = '../data/btag_SF/UL/wp_deepJet_106XUL16preVFP_v2.csv'
workingpoint='loose'
obj__ = b_new.BTagScaleFactor(filename_new, workingpoint, keep_df=True)

In [3]:
df__= obj__.df

In [4]:
df__

                                                          OperatingPoint  \
sysType         jetFlavor etaBin     ptBin       discrBin
central         0         (0.0, 2.5) (20, 1000)  (0, 1)                0
                4         (0.0, 2.5) (20, 1000)  (0, 1)                0
                5         (0.0, 2.5) (20, 1000)  (0, 1)                0
down            0         (0.0, 2.5) (20, 1000)  (0, 1)                0
                4         (0.0, 2.5) (20, 30)    (0, 1)                0
                                     (30, 50)    (0, 1)                0
                                     (50, 70)    (0, 1)                0
                                     (70, 100)   (0, 1)                0
                                     (100, 140)  (0, 1)                0
                                     (140, 200)  (0, 1)                0
                                     (200, 300)  (0, 1)                0
                                     (300, 600)  (0, 1)                0
                                     (600, 1000) (0, 1)                0
                5         (0.0, 2.5) (20, 30)    (0, 1)                0
                                     (30, 50)    (0, 1)                0
                                     (50, 70)    (0, 1)                0
                                     (70, 100)   (0, 1)                0
                                     (100, 140)  (0, 1)                0
                                     (140, 200)  (0, 1)                0
                                     (200, 300)  (0, 1)                0
                                     (300, 600)  (0, 1)                0
                                     (600, 1000) (0, 1)                0
down_correlated 0         (0.0, 2.5) (20, 1000)  (0, 1)                0
                4         (0.0, 2.5) (20, 30)    (0, 1)                0
                                     (30, 50)    (0, 1)                0
                                     (50, 70)    (0, 1)                0
                                     (70, 100)   (0, 1)                0
                                     (100, 140)  (0, 1)                0
                                     (140, 200)  (0, 1)                0
                                     (200, 300)  (0, 1)                0
...                                                                  ...
up_type3        4         (0.0, 2.5) (300, 600)  (0, 1)                0
                                     (600, 1000) (0, 1)                0
                5         (0.0, 2.5) (20, 30)    (0, 1)                0
                                     (30, 50)    (0, 1)                0
                                     (50, 70)    (0, 1)                0
                                     (70, 100)   (0, 1)                0
                                     (100, 140)  (0, 1)                0
                                     (140, 200)  (0, 1)                0
                                     (200, 300)  (0, 1)                0
                                     (300, 600)  (0, 1)                0
                                     (600, 1000) (0, 1)                0
up_uncorrelated 0         (0.0, 2.5) (20, 1000)  (0, 1)                0
                4         (0.0, 2.5) (20, 30)    (0, 1)                0
                                     (30, 50)    (0, 1)                0
                                     (50, 70)    (0, 1)                0
                                     (70, 100)   (0, 1)                0
                                     (100, 140)  (0, 1)                0
                                     (140, 200)  (0, 1)                0
                                     (200, 300)  (0, 1)                0
                                     (300, 600)  (0, 1)                0
                                     (600, 1000) (0, 1)                0
                5         (0.0, 2.5) (20, 30)    (0, 1)                0
                                     (30, 50)    (0, 1)                0
                                     (50, 70)    (0, 1)                0
                                     (70, 100)   (0, 1)                0
                                     (100, 140)  (0, 1)                0
                                     (140, 200)  (0, 1)                0
                                     (200, 300)  (0, 1)                0
                                     (300, 600)  (0, 1)                0
                                     (600, 1000) (0, 1)                0

                                                          measurementType  \
sysType         jetFlavor etaBin     ptBin       discrBin
central         0         (0.0, 2.5) (20, 1000)  (0, 1)              incl
                4         (0.0, 2.5) (20, 1000)  (0, 1)              comb
                5         (0.0, 2.5) (20, 1000)  (0, 1)              comb
down            0         (0.0, 2.5) (20, 1000)  (0, 1)              incl
                4         (0.0, 2.5) (20, 30)    (0, 1)              comb
                                     (30, 50)    (0, 1)              comb
                                     (50, 70)    (0, 1)              comb
                                     (70, 100)   (0, 1)              comb
                                     (100, 140)  (0, 1)              comb
                                     (140, 200)  (0, 1)              comb
                                     (200, 300)  (0, 1)              comb
                                     (300, 600)  (0, 1)              comb
                                     (600, 1000) (0, 1)              comb
                5         (0.0, 2.5) (20, 30)    (0, 1)              comb
                                     (30, 50)    (0, 1)              comb
                                     (50, 70)    (0, 1)              comb
                                     (70, 100)   (0, 1)              comb
                                     (100, 140)  (0, 1)              comb
                                     (140, 200)  (0, 1)              comb
                                     (200, 300)  (0, 1)              comb
                                     (300, 600)  (0, 1)              comb
                                     (600, 1000) (0, 1)              comb
down_correlated 0         (0.0, 2.5) (20, 1000)  (0, 1)              incl
                4         (0.0, 2.5) (20, 30)    (0, 1)              comb
                                     (30, 50)    (0, 1)              comb
                                     (50, 70)    (0, 1)              comb
                                     (70, 100)   (0, 1)              comb
                                     (100, 140)  (0, 1)              comb
                                     (140, 200)  (0, 1)              comb
                                     (200, 300)  (0, 1)              comb
...                                                                   ...
up_type3        4         (0.0, 2.5) (300, 600)  (0, 1)              comb
                                     (600, 1000) (0, 1)              comb
                5         (0.0, 2.5) (20, 30)    (0, 1)              comb
                                     (30, 50)    (0, 1)              comb
                                     (50, 70)    (0, 1)              comb
                                     (70, 100)   (0, 1)              comb
                                     (100, 140)  (0, 1)              comb
                                     (140, 200)  (0, 1)              comb
                                     (200, 300)  (0, 1)              comb
                                     (300, 600)  (0, 1)              comb
                                     (600, 1000) (0, 1)              comb
up_uncorrelated 0         (0.0, 2.5) (20, 1000)  (0, 1)              incl
                4         (0.0, 2.5) (20, 30)    (0, 1)              comb
                                     (30, 50)    (0, 1)              comb
                                     (50, 70)    (0, 1)              comb
                                     (70, 100)   (0, 1)              comb
                                     (100, 140)  (0, 1)              comb
                                     (140, 200)  (0, 1)              comb
                                     (200, 300)  (0, 1)              comb
                                     (300, 600)  (0, 1)              comb
                                     (600, 1000) (0, 1)              comb
                5         (0.0, 2.5) (20, 30)    (0, 1)              comb
                                     (30, 50)    (0, 1)              comb
                                     (50, 70)    (0, 1)              comb
                                     (70, 100)   (0, 1)              comb
                                     (100, 140)  (0, 1)              comb
                                     (140, 200)  (0, 1)              comb
                                     (200, 300)  (0, 1)              comb
                                     (300, 600)  (0, 1)              comb
                                     (600, 1000) (0, 1)              comb

                                                                                                     formula
sysType         jetFlavor etaBin     ptBin       discrBin
central         0         (0.0, 2.5) (20, 1000)  (0, 1)    1.33091+6.62324e-05*x+-1.19411e-07*x*x+-1.8437...
                4         (0.0, 2.5) (20, 1000)  (0, 1)        1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)
                5         (0.0, 2.5) (20, 1000)  (0, 1)        1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)
down            0         (0.0, 2.5) (20, 1000)  (0, 1)    (1.33091+6.62324e-05*x+-1.19411e-07*x*x+-1.843...
                4         (0.0, 2.5) (20, 30)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (30, 50)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (50, 70)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (70, 100)   (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (100, 140)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (140, 200)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (200, 300)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (300, 600)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (600, 1000) (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                5         (0.0, 2.5) (20, 30)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (30, 50)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (50, 70)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (70, 100)   (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (100, 140)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (140, 200)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (200, 300)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (300, 600)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (600, 1000) (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
down_correlated 0         (0.0, 2.5) (20, 1000)  (0, 1)    (1.33091+6.62324e-05*x+-1.19411e-07*x*x+-1.843...
                4         (0.0, 2.5) (20, 30)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (30, 50)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (50, 70)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (70, 100)   (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (100, 140)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (140, 200)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
                                     (200, 300)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)-0...
...                                                                                                      ...
up_type3        4         (0.0, 2.5) (300, 600)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (600, 1000) (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                5         (0.0, 2.5) (20, 30)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (30, 50)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (50, 70)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (70, 100)   (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (100, 140)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (140, 200)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (200, 300)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (300, 600)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (600, 1000) (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
up_uncorrelated 0         (0.0, 2.5) (20, 1000)  (0, 1)    (1.33091+6.62324e-05*x+-1.19411e-07*x*x+-1.843...
                4         (0.0, 2.5) (20, 30)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (30, 50)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (50, 70)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (70, 100)   (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (100, 140)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (140, 200)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (200, 300)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (300, 600)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (600, 1000) (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                5         (0.0, 2.5) (20, 30)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (30, 50)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (50, 70)    (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (70, 100)   (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (100, 140)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (140, 200)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (200, 300)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (300, 600)  (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...
                                     (600, 1000) (0, 1)    1.0007*(1.+0.000290434*x)/(1.+0.000349262*x)+0...

[477 rows x 3 columns]

In [5]:
import b_old as b_old

In [6]:
filename = '../data/DeepJet_102XSF_V1.csv'
workingpoint='loose'
obj_ = b_old.BTagScaleFactor(filename, workingpoint, keep_df=True)

In [7]:
obj_.df

                                                                    OperatingPoint  \
sysType           jetFlavor etaBin      ptBin           discrBin
central           0         (-2.5, 2.5) (20.0, 1000.0)  (0.0, 1.0)               0
                  1         (-2.5, 2.5) (20.0, 1000.0)  (0.0, 1.0)               0
                  2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)               0
down              0         (-2.5, 2.5) (20.0, 30.0)    (0.0, 1.0)               0
                                        (30.0, 50.0)    (0.0, 1.0)               0
                                        (50.0, 70.0)    (0.0, 1.0)               0
                                        (70.0, 100.0)   (0.0, 1.0)               0
                                        (100.0, 140.0)  (0.0, 1.0)               0
                                        (140.0, 200.0)  (0.0, 1.0)               0
                                        (200.0, 300.0)  (0.0, 1.0)               0
                                        (300.0, 600.0)  (0.0, 1.0)               0
                                        (600.0, 1000.0) (0.0, 1.0)               0
                  1         (-2.5, 2.5) (20.0, 30.0)    (0.0, 1.0)               0
                                        (30.0, 50.0)    (0.0, 1.0)               0
                                        (50.0, 70.0)    (0.0, 1.0)               0
                                        (70.0, 100.0)   (0.0, 1.0)               0
                                        (100.0, 140.0)  (0.0, 1.0)               0
                                        (140.0, 200.0)  (0.0, 1.0)               0
                                        (200.0, 300.0)  (0.0, 1.0)               0
                                        (300.0, 600.0)  (0.0, 1.0)               0
                                        (600.0, 1000.0) (0.0, 1.0)               0
                  2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)               0
down_correlated   2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)               0
down_uncorrelated 2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)               0
up                0         (-2.5, 2.5) (20.0, 30.0)    (0.0, 1.0)               0
                                        (30.0, 50.0)    (0.0, 1.0)               0
                                        (50.0, 70.0)    (0.0, 1.0)               0
                                        (70.0, 100.0)   (0.0, 1.0)               0
                                        (100.0, 140.0)  (0.0, 1.0)               0
                                        (140.0, 200.0)  (0.0, 1.0)               0
                                        (200.0, 300.0)  (0.0, 1.0)               0
                                        (300.0, 600.0)  (0.0, 1.0)               0
                                        (600.0, 1000.0) (0.0, 1.0)               0
                  1         (-2.5, 2.5) (20.0, 30.0)    (0.0, 1.0)               0
                                        (30.0, 50.0)    (0.0, 1.0)               0
                                        (50.0, 70.0)    (0.0, 1.0)               0
                                        (70.0, 100.0)   (0.0, 1.0)               0
                                        (100.0, 140.0)  (0.0, 1.0)               0
                                        (140.0, 200.0)  (0.0, 1.0)               0
                                        (200.0, 300.0)  (0.0, 1.0)               0
                                        (300.0, 600.0)  (0.0, 1.0)               0
                                        (600.0, 1000.0) (0.0, 1.0)               0
                  2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)               0
up_correlated     2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)               0
up_uncorrelated   2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)               0

                                                                   measurementType  \
sysType           jetFlavor etaBin      ptBin           discrBin
central           0         (-2.5, 2.5) (20.0, 1000.0)  (0.0, 1.0)            comb
                  1         (-2.5, 2.5) (20.0, 1000.0)  (0.0, 1.0)            comb
                  2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)            incl
down              0         (-2.5, 2.5) (20.0, 30.0)    (0.0, 1.0)            comb
                                        (30.0, 50.0)    (0.0, 1.0)            comb
                                        (50.0, 70.0)    (0.0, 1.0)            comb
                                        (70.0, 100.0)   (0.0, 1.0)            comb
                                        (100.0, 140.0)  (0.0, 1.0)            comb
                                        (140.0, 200.0)  (0.0, 1.0)            comb
                                        (200.0, 300.0)  (0.0, 1.0)            comb
                                        (300.0, 600.0)  (0.0, 1.0)            comb
                                        (600.0, 1000.0) (0.0, 1.0)            comb
                  1         (-2.5, 2.5) (20.0, 30.0)    (0.0, 1.0)            comb
                                        (30.0, 50.0)    (0.0, 1.0)            comb
                                        (50.0, 70.0)    (0.0, 1.0)            comb
                                        (70.0, 100.0)   (0.0, 1.0)            comb
                                        (100.0, 140.0)  (0.0, 1.0)            comb
                                        (140.0, 200.0)  (0.0, 1.0)            comb
                                        (200.0, 300.0)  (0.0, 1.0)            comb
                                        (300.0, 600.0)  (0.0, 1.0)            comb
                                        (600.0, 1000.0) (0.0, 1.0)            comb
                  2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)            incl
down_correlated   2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)            incl
down_uncorrelated 2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)            incl
up                0         (-2.5, 2.5) (20.0, 30.0)    (0.0, 1.0)            comb
                                        (30.0, 50.0)    (0.0, 1.0)            comb
                                        (50.0, 70.0)    (0.0, 1.0)            comb
                                        (70.0, 100.0)   (0.0, 1.0)            comb
                                        (100.0, 140.0)  (0.0, 1.0)            comb
                                        (140.0, 200.0)  (0.0, 1.0)            comb
                                        (200.0, 300.0)  (0.0, 1.0)            comb
                                        (300.0, 600.0)  (0.0, 1.0)            comb
                                        (600.0, 1000.0) (0.0, 1.0)            comb
                  1         (-2.5, 2.5) (20.0, 30.0)    (0.0, 1.0)            comb
                                        (30.0, 50.0)    (0.0, 1.0)            comb
                                        (50.0, 70.0)    (0.0, 1.0)            comb
                                        (70.0, 100.0)   (0.0, 1.0)            comb
                                        (100.0, 140.0)  (0.0, 1.0)            comb
                                        (140.0, 200.0)  (0.0, 1.0)            comb
                                        (200.0, 300.0)  (0.0, 1.0)            comb
                                        (300.0, 600.0)  (0.0, 1.0)            comb
                                        (600.0, 1000.0) (0.0, 1.0)            comb
                  2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)            incl
up_correlated     2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)            incl
up_uncorrelated   2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)            incl

                                                                                                              formula
sysType           jetFlavor etaBin      ptBin           discrBin
central           0         (-2.5, 2.5) (20.0, 1000.0)  (0.0, 1.0)  0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3-...
                  1         (-2.5, 2.5) (20.0, 1000.0)  (0.0, 1.0)  0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3-...
                  2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)  1.61341+-0.000566321*x+1.99464e-07*x*x+-5.0919...
down              0         (-2.5, 2.5) (20.0, 30.0)    (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (30.0, 50.0)    (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (50.0, 70.0)    (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (70.0, 100.0)   (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (100.0, 140.0)  (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (140.0, 200.0)  (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (200.0, 300.0)  (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (300.0, 600.0)  (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (600.0, 1000.0) (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                  1         (-2.5, 2.5) (20.0, 30.0)    (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (30.0, 50.0)    (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (50.0, 70.0)    (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (70.0, 100.0)   (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (100.0, 140.0)  (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (140.0, 200.0)  (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (200.0, 300.0)  (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (300.0, 600.0)  (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (600.0, 1000.0) (0.0, 1.0)  0.873139+((0.00420739*(log(x+19)*(log(x+18)*(3...
                  2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)  (1.61341+-0.000566321*x+1.99464e-07*x*x+-5.091...
down_correlated   2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)  (1.61341+-0.000566321*x+1.99464e-07*x*x+-5.091...
down_uncorrelated 2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)  (1.61341+-0.000566321*x+1.99464e-07*x*x+-5.091...
up                0         (-2.5, 2.5) (20.0, 30.0)    (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (30.0, 50.0)    (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (50.0, 70.0)    (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (70.0, 100.0)   (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (100.0, 140.0)  (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (140.0, 200.0)  (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (200.0, 300.0)  (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (300.0, 600.0)  (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (600.0, 1000.0) (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                  1         (-2.5, 2.5) (20.0, 30.0)    (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (30.0, 50.0)    (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (50.0, 70.0)    (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (70.0, 100.0)   (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (100.0, 140.0)  (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (140.0, 200.0)  (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (200.0, 300.0)  (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (300.0, 600.0)  (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                                        (600.0, 1000.0) (0.0, 1.0)  (0.873139+(0.00420739*(log(x+19)*(log(x+18)*(3...
                  2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)  (1.61341+-0.000566321*x+1.99464e-07*x*x+-5.091...
up_correlated     2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)  (1.61341+-0.000566321*x+1.99464e-07*x*x+-5.091...
up_uncorrelated   2         (0.0, 2.5)  (20.0, 1000.0)  (0.0, 1.0)  (1.61341+-0.000566321*x+1.99464e-07*x*x+-5.091...

In [8]:
import pandas

In [17]:
df = pandas.read_csv(filename, skipinitialspace=True)
discriminator = df.columns[0].split(';')[0]

In [18]:
df['jetFlavor'].value_counts()

2    11613
0     5979
1      455
Name: jetFlavor, dtype: int64

In [19]:
df = pandas.read_csv(filename_new, skipinitialspace=True)
discriminator = df.columns[0].split(';')[0]

In [15]:
df['OperatingPoint'].value_counts()

T    731
M    731
L    731
Name: OperatingPoint, dtype: int64

In [16]:
df['jetFlavor'].value_counts()

5    1086
4    1086
0      21
Name: jetFlavor, dtype: int64

In [22]:
# self._corrections = {}
import numpy
_btvflavor = numpy.array([0, 1, 2, 3])
for syst in list(df__.index.levels[0]):
    corr = df__.loc[syst]
    allbins = list(corr.index)
    # NOTE: here we force the class to assume abs(eta) based on lack of examples where signed eta is used
    edges_eta = numpy.array(sorted(set(abs(x) for tup in corr.index.levels[1] for x in tup)))
    edges_pt = numpy.array(sorted(set(x for tup in corr.index.levels[2] for x in tup)))
    edges_discr = numpy.array(sorted(set(x for tup in corr.index.levels[3] for x in tup)))
    alledges = numpy.meshgrid(_btvflavor[:-1], edges_eta[:-1], edges_pt[:-1], edges_discr[:-1], indexing='ij')
    mapping = numpy.full(alledges[0].shape, -1)

In [24]:
alledges

[array([[[[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]]],


        [[[1],
          [1],
          [1],
          [1],
          [1],
          [1],
          [1],
          [1],
          [1]]],


        [[[2],
          [2],
          [2],
          [2],
          [2],
          [2],
          [2],
          [2],
          [2]]]]), array([[[[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]]]]), array([[[[ 20],
          [ 30],
          [ 50],
          [ 70],
          [100],
          [140],
          [200],
          [300],
          [600]]],


        [[[ 20],
          [ 30],
          [ 50],
          [ 70],
          [100],
          [140],
          [200],
          [300],
          [600]]],


        [[[ 20],
          [ 30],
          [ 50],
          [ 70],
          [100],
          [140],
          [200],
          [300],
          [600]]]]), array([[[[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]]],


        [[[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]]],


        [[[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]]]])]

In [1]:
import cofe as c

In [2]:
filename_new = '../data/btag_SF/UL/wp_deepJet_106XUL16preVFP_v2.csv'
workingpoint='loose'
obj__ = c.BTagScaleFactor(filename_new, workingpoint, keep_df=True)

AttributeError: module 'cofe' has no attribute 'BTagScaleFactor'